# MINI PROJECT — STUDENT PROFILE SYSTEM
full_name = input("Enter your full name: ")
age = int(input("Enter your age: "))
student_id = input("Enter your student ID: ")
city = input("Enter your city: ")
university = input("Enter your university: ")
department = input("Enter your department: ")
email = input("Enter your email: ")
phone_number = input("Enter your phone number: ")
favorite_language = input("Enter your favorite programming language: ")
programming_goal = input("Enter your programming goal: ")
print("\n================================================")
print("              AKIBA STUDENT PROFILE")
print("================================================")

print(f"Name:                 {full_name}")
print(f"Student ID:           {student_id}")
print(f"Age:                  {age}")
print(f"City:                 {city}")
print(f"University:            {university}")
print(f"Department:            {department}")
print(f"Email:                 {email}")
print(f"Phone:                 {phone_number}")
print(f"Favorite Language:     {favorite_language}")

print("\nProgramming Goal:")
print(programming_goal)

print("================================================")